theycantrevealus/PDC00001

- api/app/Inventori.php
- api/app/Modul.php
- client/head.php
- client/pages/master/inventori/kategori/index.php
- client/script/master/inventori/kategori/index.php
> contoh felix

- api/app/Contoh.php
- api/app/Query.php
1. Tambah fitur offset dan limit
2. Contoh penggunaan pada class contoh
> Fitur Offset dan Limit

- api/app/Contoh.php
- api/app/Query.php
Query Manager new feature apply
> Query manager

- client/pages/master/inventori/kategori/index.php
- client/pages/master/inventori/kategori/tambah.php
- client/pages/master/inventori/satuan/index.php
- client/script/master/inventori/kategori/index.php
- client/script/master/inventori/satuan/index.php
Master INV Kategori, Master INV Satuan
> Data master

- api/app/Contoh.php
- api/app/Inventori.php
- api/app/Penjamin.php
- api/app/Poli.php
- api/app/Query.php
- client/head.php
- client/pages/master/inventori/tambah.php
- client/pages/master/poli/poli/edit.php
- client/script/master/inventori/tambah.php
- client/script/master/poli/poli/edit.php
- client/script/master/poli/poli/index.php
- client/sidemenu.php
1. Fitur _edit_ poli sudah selesai
2. Fitur tampilkan _detail_ tindakan poli pada halaman _index_ poli akan di nonaktifkan sementara, menunggu perbaikan _query builder_ untuk _join_
> Fitur Edit Poli

- api/app/Pasien.php
- client/pages/pasien/index.php
- client/pages/pasien/tambah.php
- client/script/pasien/index.php
- client/script/pasien/tambah.php
1. Tabel Pasien
2. Tambah Pasien
> Data Pasien

- api/app/Antrian.php
- api/app/Pegawai.php
- api/app/Penjamin.php
- api/app/Poli.php
- api/app/Tindakan.php
- client/pages/antrian_resepsionis/index.php
- client/pages/antrian_resepsionis/tambah.php
- client/pages/rawat_jalan/dokter/action-panel.php
- client/pages/rawat_jalan/dokter/antrian.php
- client/pages/rawat_jalan/dokter/asesmen-awal.php
- client/pages/rawat_jalan/dokter/asesmen-rawat.php
- client/pages/rawat_jalan/dokter/index.php
- client/pages/rawat_jalan/dokter/resep.php
- client/pages/rawat_jalan/dokter/tindakan.php
- client/script/antrian_resepsionis/index.php
- client/script/antrian_resepsionis/tambah.php
- client/script/rawat_jalan/dokter/antrian.php
- client/script/rawat_jalan/dokter/index.php
Update feature rawat jalan. Add pasien to Antrian
> Rawat jalan Feature Updated

- api/app/Query.php
> Fix update query segment. NULL Management Fix

- api/app/Antrian.php
- api/app/Asesmen.php
- api/app/Penjamin.php
- api/app/Poli.php
- api/app/Query.php
- client/pages/rawat_jalan/dokter/antrian.php
- client/pages/rawat_jalan/dokter/asesmen-awal.php
- client/pages/rawat_jalan/dokter/index.php
- client/pages/rawat_jalan/dokter/resep.php
- client/pages/rawat_jalan/dokter/review.php
- client/script/rawat_jalan/dokter/antrian.php
- client/script/rawat_jalan/dokter/index.php
Merge master test. Review PondokCoder Server
> Rawat jalan

- api/app/Antrian.php
- api/app/Asesmen.php
- api/app/AssesmenRawatJalan.php
- api/app/Poli.php
- client/pages/rawat_jalan/perawat/antrian.php
- client/pages/rawat_jalan/perawat/index.php
- client/pages/rawat_jalan/resepsionis/tambah.php
- client/script/rawat_jalan/perawat/antrian.php
- client/script/rawat_jalan/perawat/index.php
- client/script/rawat_jalan/resepsionis/tambah.php
1. Move method in AsesmenRawatJalan.php to Asesmen.php
2. Fixing Antrian class
3. Fixing Poli class
> Fixing Asesmen Rawat

- api/app/Antrian.php
- api/app/Pasien.php
- api/app/Radiologi.php
- client/pages/radiologi/antrian.php
- client/pages/radiologi/gambar.php
- client/pages/radiologi/hasil.php
- client/pages/radiologi/index.php
- client/script/radiologi/antrian.php
- client/script/radiologi/index.php
1. Antrian api, create new function for call Antrian data
2. Pasien api, create new public function for get Pasien data
3. Radiologi fill form Tindakan Keterangan and Kesimpulan
4. Radiologi upload and remove pdf document from radiologi scan result
> Radiologi merge to master

- client/script/radiologi/index.php
1. Fixing datatable for radiologi queue
> 1. Fixing datatable for radiologi queue

- api/app/Antrian.php
- api/app/Pasien.php
- api/app/Radiologi.php
- client/pages/radiologi/antrian.php
- client/pages/radiologi/gambar.php
- client/pages/radiologi/hasil.php
- client/pages/radiologi/index.php
- client/script/radiologi/antrian.php
- client/script/radiologi/index.php
This merge happen 'cause branch lab using api from master branch
> Merge for using master branch function and api for lab branch

- api/app/Radiologi.php
1. Fixing api for Radiologi
2. Change field in radiologi_order, antrian -> asesmen
> Fixing api for Radiologi

- client/script/radiologi/antrian.php
1. Fixing double upload document (lampiran)
2. Add refresh after add document (lampiran)
> Bugs double upload document lampiran Radiologi

- api/app/DeliveryOrder.php
- client/pages/inventori/do/tambah.php
- client/script/inventori/do/tambah.php
Fix Error DO pada issue tentang tanggal kadaluarsa check
DO tidak dapat di save sebelum tanggal kadaluarsa diisi.
Closes #109
> Fix Error DO pada issue

- api/app/Tindakan.php
- client/pages/master/tindakan/rawat_inap/index.php
- client/pages/master/tindakan/rawat_jalan/index.php
- client/script/master/poli/edit.php
- client/script/master/poli/tambah.php
- client/script/master/tindakan/rawat_inap/index.php
- client/script/master/tindakan/rawat_jalan/index.php
1. Split tindakan rawat jalan and tindakan rawat inap
2. CRUD module for tindakan rawat inap and rawat jalan
> Split module for tindakan rawat jalan dan rawat inap

- api/app/Antrian.php
- api/app/Invoice.php
- client/index.php
- client/pages/rawat_jalan/resepsionis/tambah.php
- client/script/kasir/pasien/index.php
- client/script/rawat_jalan/resepsionis/tambah.php
Implementasi struktur kelas biaya baru pada rawat jalan. Biaya kartu dan konsultasi sudah mengikuti struktur baru
> Fix biaya kartu dan konsultasi mengikuti struktur biaya baru

- api/app/Apotek.php
- api/app/Asesmen.php
- api/app/Invoice.php
- api/app/Poli.php
- api/app/Tindakan.php
- client/index.php
- client/pages/apotek/proses/index.php
- client/pages/rawat_jalan/dokter/index.php
- client/pages/rawat_jalan/perawat/index.php
- client/script/apotek/proses/index.php
- client/script/display/index.php
- client/script/kasir/pasien/index.php
- client/script/master/tindakan/rawat_jalan/index.php
- client/script/rawat_jalan/dokter/antrian.php
Pemanggilan sudah diurutkan sesuai dengan waktu pemanggilan dan sistem manajer pemanggilan sudah  memanggil secara recursive
> Fix pemanggilan bertimpa

- api/app/Radiologi.php
Echancement: 
1. Checking count of listTindakan before add order to database
2. Feature to delete order
> Echancement, checking count of listTindakan and feature to delete order

- api/app/Antrian.php
- api/app/Asesmen.php
- api/app/Icd.php
- client/header.php
- client/pages/rawat_jalan/dokter/antrian.php
- client/pages/rawat_jalan/dokter/asesmen-awal.php
- client/pages/rawat_jalan/perawat/halaman1.php
- client/pages/rawat_jalan/perawat/index.php
- client/pages/system/login.php
- client/script/rawat_jalan/dokter/antrian.php
- client/script/rawat_jalan/perawat/antrian.php
- client/script/rawat_jalan/perawat/index.php
> Multi ICD asesmen medis

- api/app/Radiologi.php
- api/app/Tindakan.php
- client/pages/laboratorium/lab-single-verif.php
- client/pages/pasien/dokter/lab-single.php
- client/script/laboratorium/index.php
- client/script/master/tindakan/laboratorium/index.php
- client/script/master/tindakan/radiologi/index.php
- client/script/radiologi/antrian.php
- client/script/radiologi/index.php
1. Labor 1 DPJP dan 1 tombol verifikasi
2. Radiologi ubah nilai total invoice setelah verfikasi
3. Warning harga pada verifikasi tindakan penunjang
> Verifikasi Tindakan Penunjang

- api/app/Inventori.php
- client/pages/inventori/stok/mutasi/index.php
- client/script/inventori/do/tambah.php
- client/script/inventori/stok/mutasi/index.php
- client/script/inventori/stok/mutasi/tambah.php
> Buka Fitur Mutasi

- api/app/Asesmen.php
- client/pages/rawat_jalan/perawat/halaman1.php
- client/script/rawat_jalan/perawat/antrian.php
> Asesmen Kebidanan

- api/app/Asesmen.php
- client/script/apotek/proses/index.php
- client/script/apotek/selesai/index.php
- client/script/rawat_jalan/dokter/antrian.php
- client/script/rawat_jalan/resepsionis/index.php
Resep, Racikan allow 0 aturan pakai. Parse integer handler
> Apotek + Asesmen Dokter untuk apotek

- api/app/Antrian.php
- api/app/Asesmen.php
- client/pages/rawat_jalan/perawat/igd_1.php
- client/pages/rawat_jalan/perawat/igd_2.php
- client/pages/rawat_jalan/perawat/igd_3.php
- client/script/apotek/proses/antrian.php
- client/script/apotek/selesai/index.php
- client/script/inventori/stok/point/index.php
- client/script/rawat_jalan/dokter/antrian.php
1. Form asesmen rawat IGD biasa + bidan
2. Fix racikan detail tidak tersimpan
3. Filter fix pisah penyerahan obat IGD dan poli biasa
> Update dan fix

- client/pages/rawat_jalan/dokter/asesmen-awal.php
Disable input informasi pemeriksaan oleh perawat di dokter untuk Issue Closes #255
> Disable input informasi pemeriksaan oleh perawat di dokter.

- api/app/Aplicares.php
- api/app/Authorization.php
- api/app/BPJS.php
- api/app/Inventori.php
- api/app/JKN.php
- client/head.php
- client/pages/rawat_jalan/resepsionis/index.php
- client/script/aplicares/kamar/index.php
- client/script/rawat_jalan/resepsionis/index.php
- client/script/rawat_jalan/resepsionis/tambah.php
- miscellaneous/print_template/pasien_kartu.php
> Ptb Back Up

- api/app/Authorization.php
- api/app/Contoh.php
- api/app/DeliveryOrder.php
- api/app/Inventori.php
- api/app/Invoice.php
- api/app/Laporan.php
- api/app/PO.php
- client/pages/igd/dokter/action-panel.php
- client/pages/inventori/amprah/proses/index.php
- client/pages/inventori/do/index.php
- client/pages/inventori/do/tambah.php
- client/pages/laporan/keuangan/index.php
- client/pages/laporan/kunjungan_perpoli/index.php
- client/pages/rawat_inap/dokter/asesmen-awal.php
- client/script/igd/dokter/antrian.php
- client/script/inventori/amprah/proses/index.php
- client/script/inventori/do/index.php
- client/script/inventori/do/tambah.php
- client/script/laporan/keuangan/index.php
- client/script/laporan/kunjungan_perpoli/index.php
- client/script/rawat_inap/dokter/antrian.php
- client/script/rawat_jalan/resepsionis/index.php
- miscellaneous/print_template/do_detail.php
- miscellaneous/print_template/laporan_keuangan.php
- miscellaneous/print_template/laporan_kunjungan_perpoli.php
1. Bukti Amprah
2. DO limit PO barang sudah sampai semua hilang dari list
3. Cetak DO
4. BackEnd data proses kartu stok
> Fix modul inventori

- client/script/kasir/pasien/index.php
Fixed pagination kasir
Closing #268
> PDC00001-268 Pagination Kasir

- api/app/Laboratorium.php
- client/script/master/laboratorium/index.php
Pagination Master Laboratorium
> Labor pagination

- api/app/Asesmen.php
- api/app/Invoice.php
- api/app/Laboratorium.php
- api/app/Pegawai.php
- client/pages/igd/dokter/antrian.php
- client/pages/pasien/dokter/lab-single.php
- client/script/igd/dokter/antrian.php
- client/script/kasir/pasien/index.php
- client/script/pasien/dokter/index.php
- client/script/rawat_jalan/dokter/antrian.php
1. Retur biaya konsultasi
2. Odontogram silica dan composite
3. Resep dan Racikan pada IGD
> Enhancement

- api/app/Apotek.php
- api/app/Inap.php
- api/app/Inventori.php
- client/script/apotek/resep/view.php
- client/script/inventori/stok/kartu/index.php
- client/script/inventori/stok/kartu/view.php
- client/script/kasir/pasien/index.php
- client/script/rawat_inap/perawat/asesmen-detail.php
Fix pengecekan stok pada saat pemberian obat pasien ranap [PERAWAT]
> Rawat inap

- api/app/Apotek.php
- api/app/Laboratorium.php
- api/app/Radiologi.php
- client/pages/inventori/amprah/proses/index.php
- client/pages/rawat_jalan/dokter/tindakan.php
- client/script/inventori/amprah/index.php
- client/script/inventori/amprah/proses/index.php
- client/script/laboratorium/verifikasi/index.php
- client/script/rawat_jalan/dokter/antrian.php
- miscellaneous/print_template/do_detail.php
- miscellaneous/print_template/lab_hasil.php
- miscellaneous/print_template/rad_hasil.php
Fitur setting surat menyurat departemen
> Latest Update merge

- client/pages/inventori/stok/mutasi/tambah.php
- client/script/inventori/stok/mutasi/tambah.php
> Feature Request

- api/app/Antrian.php
- api/app/Apotek.php
- api/app/Asesmen.php
- api/app/Inventori.php
- client/pages/apotek/selesai/index.php
- client/script/apotek/cancelation/index.php
- client/script/apotek/proses/index.php
- client/script/apotek/resep/index.php
- client/script/apotek/selesai/index.php
- client/script/inventori/stok/kartu/index.php
- client/script/rawat_inap/perawat/index.php
- client/script/rawat_jalan/resepsionis/tambah.php
1. Stok obat di simrsv2 gak = fisik, jd stok gak real shg mjd kendala saat memverif. 
2. Loading lama: 
- Saat memverif sering reconnecting. 
- Saat memproses resep, setelah selesai mencetak 1-2 resep, sistemnya jadi not responding, meminta utk re-log in shg memperlambat pelayanan krn mengeprint 1-2 resep lalu log in, begitu seterusnya. 
- resep yg sudah lunas di kasir saat dicetak di aptk masih Rp 0, stlh re-log in bbrp x baru muncul resep dg harga obat yg benar.
3. Resep dari poli, lama masuknya ke sistem apotek, padahal saat diconfirm ke poli ybs resep sudah di-oke kan sejak tadi. 
4. Masih ada resep yg harganya Rp. 0. 
📒 Informasi RM pasien?
5. Masih ada resep yg kosong (tdk ada item obatnya).
📒 Informasi RM pasien? 
6. Masih ditemukan resep yg dpt diverif/terverif 2x (entah krn …
> Uji Coba Update dan Fix

- api/app/Antrian.php
- api/app/Apotek.php
- api/app/Asesmen.php
- api/app/IGD.php
- api/app/Inap.php
- api/app/Inventori.php
- api/app/SO.php
- client/builder.php
- client/pages/apotek/selesai/index.php
- client/pages/inventori/stok/importso/index.php
- client/pages/rawat_jalan/resepsionis/index.php
- client/script.php
- client/script/apotek/cancelation/index.php
- client/script/apotek/proses/index.php
- client/script/apotek/resep/index.php
- client/script/apotek/resep/view.php
- client/script/apotek/selesai/index.php
- client/script/display/index.php
- client/script/igdv2/perawat/asesmen-detail.php
- client/script/inventori/stok/importso/index.php
- client/script/inventori/stok/kartu/index.php
- client/script/inventori/stok/penyesuaian/index.php
- client/script/rawat_inap/perawat/asesmen-detail.php
- client/script/rawat_inap/perawat/index.php
- client/script/rawat_jalan/resepsionis/index.php
- client/script/rawat_jalan/resepsionis/tambah.php
- miscellaneous/print_template/resep_view.php
Saran agar aman live di pull saat jam pelayanan rawat jalan sepi
> Testing mode - Fixed Tested for Launch

- api/app/CPPT.php
- client/builder.php
- client/pages/pasien/cppt-single.php
- client/script/inventori/stok/kartu/index.php
- client/script/rawat_jalan/resepsionis/index.php
1. Aturan pakai di rapel ke keterangan resep dan racikan
2. Memunculkan kekurangan informasi satuan sediaan pada verifikasi
3. Enhance penyimpanan resep dan racikan pada dokter
Tahapan update yg perlu diperhatikan
1. tambahkan client/plugin cdndt (dikirimkan lewat whatsapp)
2. ubah tipe data pada tabel resep detail aturan_pakai = character varying
3. update custom.css (dikirimkan lewat whatsapp)
4. tambahkan client/plugins pdfjs/pdf2.js (dikirimkan lewat whatsapp)
5. ubah tipe data pada tabel racikan satuan_konsumsi character varying
> Pengujian Model Peresepan Fix

- client/script/apotek/resep/view.php
Keterangan satuan sediaan dan pemakaian
> Split keterangan satuan pemakaian pada verifikator
